spring.datasource.url=jdbc:mysql://localhost:3306/mdd
spring.datasource.username=mdd_user
spring.datasource.password=mdd_pass_123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
